// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn3dsDmBBjpRPMLELd5rq4ARmFWb8z4Ng',
    appId: '1:937050865176:web:c325863bcd29d96bc94d6d',
    messagingSenderId: '937050865176',
    projectId: 'ieee-organizer',
    authDomain: 'ieee-organizer.firebaseapp.com',
    storageBucket: 'ieee-organizer.firebasestorage.app',
    measurementId: 'G-TNPWZTPFHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL4hgZ-7edMg6F_5Ec-UDGJeY6dLD2E_g',
    appId: '1:937050865176:android:75dcedbaa344d003c94d6d',
    messagingSenderId: '937050865176',
    projectId: 'ieee-organizer',
    storageBucket: 'ieee-organizer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABu7T61ie1w-Pe0oDArSBuNFTOeMB9xA8',
    appId: '1:937050865176:ios:fbfabd4ce64c8f83c94d6d',
    messagingSenderId: '937050865176',
    projectId: 'ieee-organizer',
    storageBucket: 'ieee-organizer.firebasestorage.app',
    androidClientId: '937050865176-1mnr6ehbe1v44v2be81l2f3kg8cg5at5.apps.googleusercontent.com',
    iosClientId: '937050865176-800b4hlu19gea7sm99k69d8u0futl4e6.apps.googleusercontent.com',
    iosBundleId: 'com.example.ieeeOrganizer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABu7T61ie1w-Pe0oDArSBuNFTOeMB9xA8',
    appId: '1:937050865176:ios:fbfabd4ce64c8f83c94d6d',
    messagingSenderId: '937050865176',
    projectId: 'ieee-organizer',
    storageBucket: 'ieee-organizer.firebasestorage.app',
    androidClientId: '937050865176-1mnr6ehbe1v44v2be81l2f3kg8cg5at5.apps.googleusercontent.com',
    iosClientId: '937050865176-800b4hlu19gea7sm99k69d8u0futl4e6.apps.googleusercontent.com',
    iosBundleId: 'com.example.ieeeOrganizer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn3dsDmBBjpRPMLELd5rq4ARmFWb8z4Ng',
    appId: '1:937050865176:web:c2b2df8d4c997ff6c94d6d',
    messagingSenderId: '937050865176',
    projectId: 'ieee-organizer',
    authDomain: 'ieee-organizer.firebaseapp.com',
    storageBucket: 'ieee-organizer.firebasestorage.app',
    measurementId: 'G-13KY4D0MH8',
  );

}